### ISSUE TITLE
Auto-build on tag

### ISSUE THREAD

**Issue by Frenzie** [koreader/virdevenv#82]
Basic reference https://dev.to/github/publishing-a-docker-image-to-githubs-container-repository-4n50

```yaml
name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
       docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
       docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
```
